### ANN (ARTIFICIAL NEURAL NETWORK):
* AN Artificial neural network is an computational model(means mathematical and algorithmic strucutre)  inspired by the way biological neural network in the human brain work it is a key technology in deep learning and mechine learning.
* ANN are designed to recognize patterns and relationships in data through a process of learning,generalizing from examples.

### How does ANN Work.
* An ANN consists of layer of interconnceted nodes(neurons),each connection has weight and each neuron has an associated bias.the network process information through these connection and neurons using mathematical functions.

### Working of ANN
* Forward propagation
* loss calculation
* Back propagation
* weight update(optimization)
* Iteration



In [69]:
import pandas as pd


In [70]:
df=pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [71]:
df.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   
5               Yes     Fiber optic             No  ...              Yes   
6               Yes     Fiber optic             No  ...               No   
7  No phone service             DSL            Yes  ...               No   
8               Yes     Fiber optic             No  ...              Yes   
9                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   
5          No         Yes             Yes  Month-to-month              Yes   
6          No         Yes              No  Month-to-month              Yes   
7          No          No              No  Month-to-month               No   
8         Yes         Yes             Yes  Month-to-month              Yes   
9          No          No              No        One year               No   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  
5           Electronic check          99.65         820.5   Yes  
6    Credit card (automatic)          89.10        1949.4    No  
7               Mailed check          29.75         301.9    No  
8           Electronic check         104.80       3046.05   Yes  
9  Bank transfer (automatic)          56.15       3487.95    No  

[10 rows x 21 columns]

In [72]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [73]:
df.shape

(7043, 21)

In [74]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

#### Clean& PReprocess Data

In [75]:
df.drop('customerID',axis=1,inplace=True)  # drop customerid it is not useful


In [76]:
#  convert totalcharges to numeric(has blanks)
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].median(),inplace=True)

#convert target to binary
df['Churn']=df['Churn'].map({'yes':1,'No':0})

#### Encode Categorical VAriables

In [77]:
from sklearn.preprocessing import LabelEncoder

In [78]:
# identify categorical columns
cat_cols=df.select_dtypes(include=['object']).columns

In [79]:
#label encode binary columns
binary_cols=[col for col in cat_cols if df[col].nunique()==2]
for col in binary_cols:
  df[col]=LabelEncoder().fit_transform(df[col])

In [80]:
#one hot encode others
df=pd.get_dummies(df,columns=[col for col in cat_cols if col not in binary_cols])

In [81]:
df.dtypes

gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                      float64
MultipleLines_No                              bool
MultipleLines_No phone service                bool
MultipleLines_Yes                             bool
InternetService_DSL                           bool
InternetService_Fiber optic                   bool
InternetService_No                            bool
OnlineSecurity_No                             bool
OnlineSecurity_No internet service            bool
OnlineSecurity_Yes                            bool
OnlineBackup_No                               bool
OnlineBackup_No internet service              bool
OnlineBackup_Yes                              bool
DeviceProtection_No                           bool
DeviceProtection_No internet service          bool
DeviceProtection_Yes                          bool
TechSupport_No                                bool
TechSupport_No internet service               bool
TechSupport_Yes                               bool
StreamingTV_No                                bool
StreamingTV_No internet service               bool
StreamingTV_Yes                               bool
StreamingMovies_No                            bool
StreamingMovies_No internet service           bool
StreamingMovies_Yes                           bool
Contract_Month-to-month                       bool
Contract_One year                             bool
Contract_Two year                             bool
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
dtype: object

## Feature Scaling and Splitting


In [82]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [83]:
x=df.drop('Churn',axis=1).values
y=df['Churn'].values

In [84]:
scaler=StandardScaler()
x=scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [85]:
x_train

array([[-1.00955867, -0.43991649, -0.96662231, ..., -0.52504733,
        -0.71102597,  1.83551265],
       [-1.00955867, -0.43991649, -0.96662231, ..., -0.52504733,
        -0.71102597, -0.54480692],
       [ 0.99053183, -0.43991649,  1.03453023, ..., -0.52504733,
         1.40641839, -0.54480692],
       ...,
       [ 0.99053183, -0.43991649,  1.03453023, ..., -0.52504733,
         1.40641839, -0.54480692],
       [ 0.99053183,  2.27315869, -0.96662231, ..., -0.52504733,
         1.40641839, -0.54480692],
       [ 0.99053183, -0.43991649, -0.96662231, ...,  1.90459021,
        -0.71102597, -0.54480692]])

In [86]:
x_test

array([[-1.00955867, -0.43991649,  1.03453023, ..., -0.52504733,
         1.40641839, -0.54480692],
       [ 0.99053183, -0.43991649, -0.96662231, ..., -0.52504733,
        -0.71102597, -0.54480692],
       [-1.00955867, -0.43991649,  1.03453023, ..., -0.52504733,
        -0.71102597,  1.83551265],
       ...,
       [ 0.99053183, -0.43991649,  1.03453023, ..., -0.52504733,
        -0.71102597, -0.54480692],
       [-1.00955867, -0.43991649,  1.03453023, ...,  1.90459021,
        -0.71102597, -0.54480692],
       [ 0.99053183, -0.43991649, -0.96662231, ..., -0.52504733,
        -0.71102597,  1.83551265]])

In [87]:
y_train,y_test

(array([ 0.,  0., nan, ...,  0., nan,  0.]),
 array([nan,  0.,  0., ...,  0.,  0., nan]))

## Build the ANN model

In [88]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader,TensorDataset

In [89]:
# convert to tensors
x_train_t=torch.tensor(x_train,dtype=torch.float32)
y_train_t=torch.tensor(y_train,dtype=torch.float32).view(-1,1)

x_test_t=torch.tensor(x_test,dtype=torch.float32)
y_test_t=torch.tensor(y_test,dtype=torch.float32).view(-1,1)

train_data=TensorDataset(x_train_t,y_train_t)
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)

## Define the model

In [90]:
class ANNModel(nn.Module):
  def __init__(self,input_dim):
    super().__init__()
    # self.fc1=nn.Linear(input_dim,64)
    # self.fc2=nn.Linear(64,32)
    # self.out=nn.Linear(32,1)
    # self.relu=nn.ReLU()
    # self.dropout=nn.Dropout(0.3)
    self.layers=nn.Sequential(
        nn.Linear(input_dim,128),
        nn.BatchNorm1d(128),
        nn.ReLU(),
        nn.Dropout(0.4),
        nn.Linear(128,64),
        nn.Dropout(0.3),
        nn.Linear(64,1)
    )

  def forward(self,x):
    # x=self.relu(self.fc1(x))
    # x=self.dropout(x)
    # x=self.relu(self.fc2(x))
    # x=self.out(x)
    x = self.layers(x)
    return x

model=ANNModel(x.shape[1])

### Train the Model

In [ ]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005, weight_decay=1e-5)

loss_fn=nn.BCEWithLogitsLoss()

epochs=50
for epoch in range(epochs):
  model.train()
  total_loss=0
  for x_batch,y_batch in train_loader:
    optimizer.zero_grad()
    y_pred=model(x_batch)
    loss=loss_fn(y_pred,y_batch)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()
  print(f"epoch {epoch+1} | loss: {total_loss/len(train_loader):.4f}")




epoch 1 | loss: nan
epoch 2 | loss: nan
epoch 3 | loss: nan
epoch 4 | loss: nan
epoch 5 | loss: nan
epoch 6 | loss: nan
epoch 7 | loss: nan
epoch 8 | loss: nan
epoch 9 | loss: nan
epoch 10 | loss: nan
epoch 11 | loss: nan
epoch 12 | loss: nan
epoch 13 | loss: nan
epoch 14 | loss: nan
epoch 15 | loss: nan
epoch 16 | loss: nan
epoch 17 | loss: nan
epoch 18 | loss: nan
epoch 19 | loss: nan
epoch 20 | loss: nan


### Evaluate the model

In [92]:
from sklearn.metrics import accuracy_score,classification_report
import warnings
warnings.filterwarnings('ignore')

In [93]:
model.eval()
with torch.no_grad():
    # 1. Predict using model
    raw_preds = model(x_test_t)

    # 2. Replace any NaNs in predictions (safety step)
    raw_preds = torch.nan_to_num(raw_preds, nan=0.0)

    # 3. Apply sigmoid and round to get class labels (0 or 1)
    preds = torch.sigmoid(raw_preds).round()

    # 4. Convert to NumPy arrays
    preds_np = preds.numpy().astype(int)
    y_test_np = y_test_t.numpy().astype(int)

    # 5. Evaluate
    acc = accuracy_score(y_test_np, preds_np)
    print(f"Test Accuracy: {acc * 100:.2f}%")
    print(classification_report(y_test_np, preds_np, target_names=["No Churn", "Churn"]))


Test Accuracy: 73.53%
              precision    recall  f1-score   support

    No Churn       0.00      0.00      0.00       373
       Churn       0.74      1.00      0.85      1036

    accuracy                           0.74      1409
   macro avg       0.37      0.50      0.42      1409
weighted avg       0.54      0.74      0.62      1409

